name: nutrition_ai_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.8
  delightful_toast: ^1.1.0
  dio: ^5.7.0
  dotted_border: ^2.1.0
  easy_date_timeline: ^2.0.6
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/json/
    - .env

  fonts:
    - family: NimbusSans
      fonts:
        - asset: assets/fonts/NimbusSans/NimbusSanL-Reg.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf

    - family: Viga
      fonts:
        - asset: assets/fonts/Viga/Viga-Regular.ttf
